name: 🗣️ Report a player
description: ⚠️ Report inappropriate behavior or concerns related to the JeriCraft Discord and Minecraft servers.
title: "[REPORT] <offender>"
labels: [ "Report" ]
assignees: Chalwk
body:
  - type: input
    id: YourUsername
    attributes:
      label: Your Minecraft Username
      description: Enter your Minecraft username.
      placeholder: Your Minecraft Username
    validations:
      required: true
  - type: input
    id: ReportedPlayerUsername
    attributes:
      label: Reported Player's Minecraft Username
      description: Enter the username of the player you are reporting.
      placeholder: Reported Player's Minecraft Username
    validations:
      required: true
  - type: input
    id: DateAndTime
    attributes:
      label: 📅 Date and Time of Incident
      description: Enter the date and time of the incident in MM/DD/YYYY - HH:MM (Timezone) format.
      placeholder: MM/DD/YYYY - HH:MM (Timezone)
    validations:
      required: true
  - type: textarea
    id: Description
    attributes:
      label: 📝 Description of Incident
      description: Provide a detailed description of the incident, including any relevant context, actions, and statements made by the reported player.
      placeholder: Description of Incident
    validations:
      required: true
  - type: textarea
    id: Evidence
    attributes:
      label: 🔍 Evidence (if applicable)
      description: Include any screenshots, videos, or chat logs related to the incident. Upload images or videos to an image hosting site like Imgur and provide the link.
      placeholder: Evidence (if applicable)
  - type: textarea
    id: AdditionalInformation
    attributes:
      label: 📝 Additional Information
      description: Add any other context or information that may be relevant to the report.
      placeholder: Additional Information
  - type: markdown
    attributes:
      value: |
        **📷 Screenshots**
        > Include any relevant screenshots to help illustrate your report.
        >
        >
        > 🙌 Thank you
        >
        > **We appreciate your effort in reporting this incident to maintain a fair and respectful environment on the server.**