name: Halo Tournament Bracket Creation
description: Use this template to create a custom tournament bracket system.
title: "[Bracket Creation] <Tournament Name>"
labels: [ "Tournament Bracket" ]
assignees: Chalwk
body:
  - type: markdown
    attributes:
      value: |
        **📌 Tournament Bracket Creation**
        > Use this template to create a custom bracket system for the JeriCraft community's Halo tournament.
        > Provide the necessary information to design the bracket, including the teams, number of rounds, and match format.
        > Be sure to include:
        > - Tournament name
        > - Number of teams
        > - Number of rounds
        > - Custom rules for each round
        > - Format (e.g., single elimination, double elimination, round robin)
        > - Game mode and map settings

        ---
        
        ## **Tournament Bracket Details**
        
        ### **1. Tournament Name**
        - **Tournament Name**: `<Enter Tournament Name>`
        
        ### **2. Number of Teams**
        - **Total Teams**: `<Enter the number of teams>`
        
        ### **3. Number of Rounds**
        - **Rounds**: `<Enter the number of rounds>` (e.g., 3 rounds)

        ### **4. Format**
        - **Tournament Format**: `<Select Format>` (Single Elimination, Double Elimination, Round Robin)

        ### **5. Custom Rules for Each Round**
        - Round 1 Rules: `<Enter custom rules or settings for Round 1>`
        - Round 2 Rules: `<Enter custom rules or settings for Round 2>`
        - Round 3 Rules: `<Enter custom rules or settings for Round 3>`
        
        ### **6. Game Mode & Map Settings**
        - **Game Mode**: `<Select Game Mode>` (Slayer, Capture the Flag, King of the Hill, etc.)
        - **Map Restrictions**: `<Enter map restrictions or specify "All Maps">`
        
        ### **7. Team List**
        - **Team 1**: `<Enter Team 1 Name>`
        - **Team 2**: `<Enter Team 2 Name>`
        - **Team 3**: `<Enter Team 3 Name>`
        - **Team 4**: `<Enter Team 4 Name>`
        - (Continue with as many teams as needed)
        
        ---
        
        ## **Generated Bracket System**
        
        Once the above details are provided, a custom tournament bracket will be created based on your selections. This can then be updated as the tournament progresses. Below is a **sample structure** based on the inputs above.

        ### **Round 1:**
        | Match | Team 1        | Team 2        | Map           | Game Mode      | Winner | Points |
        |-------|---------------|---------------|---------------|----------------|--------|--------|
        | 1     | Team 1        | Team 2        | Blood Gulch   | Slayer         | TBD    | TBD    |
        | 2     | Team 3        | Team 4        | Battle Creek  | Capture the Flag | TBD    | TBD    |
        
        ### **Round 2:**
        | Match | Team 1        | Team 2        | Map           | Game Mode      | Winner | Points |
        |-------|---------------|---------------|---------------|----------------|--------|--------|
        | 1     | Winner of Match 1 | Winner of Match 2 | Blood Gulch   | Slayer         | TBD    | TBD    |

        ### **Finals:**
        | Match | Team 1        | Team 2        | Map           | Game Mode      | Winner | Points |
        |-------|---------------|---------------|---------------|----------------|--------|--------|
        | 1     | Winner of Final 1 | TBD           | Blood Gulch   | Slayer         | TBD    | TBD    |

  - type: input
    id: tournament_name
    attributes:
      label: Tournament Name
      description: What is the name of the tournament?
      placeholder: "Enter the tournament name"
    validations:
      required: true

  - type: input
    id: number_of_teams
    attributes:
      label: Number of Teams
      description: How many teams will participate in the tournament?
      placeholder: "Enter the number of teams"
    validations:
      required: true

  - type: input
    id: number_of_rounds
    attributes:
      label: Number of Rounds
      description: How many rounds will the tournament have?
      placeholder: "Enter the number of rounds"
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: Tournament Format
      description: Select the tournament format.
      options:
        - Single Elimination
        - Double Elimination
        - Round Robin
    validations:
      required: true

  - type: textarea
    id: custom_rules
    attributes:
      label: Custom Rules for Each Round
      description: Provide any custom rules or settings for each round.
      placeholder: "Enter rules for Round 1, 2, and 3"
    validations:
      required: false

  - type: dropdown
    id: game_mode
    attributes:
      label: Game Mode
      description: Select the game mode.
      options:
        - Slayer
        - Capture the Flag
        - King of the Hill
        - Oddball
        - Custom (specify below)
    validations:
      required: true

  - type: input
    id: allowed_maps
    attributes:
      label: Map Settings
      description: Specify which maps are allowed (or type "All Maps").
      placeholder: "Enter allowed maps"
    validations:
      required: true

  - type: textarea
    id: team_list
    attributes:
      label: Team List
      description: Provide the names of the teams participating in the tournament.
      placeholder: "Enter team names (e.g., Team A, Team B)"
    validations:
      required: true

  - type: input
    id: registration_deadline
    attributes:
      label: Registration Deadline
      description: When should player/team registrations close?
      placeholder: "e.g., 2025-02-05, 11:59 PM UTC"
    validations:
      required: true

  - type: input
    id: organizer_name
    attributes:
      label: Organizer Name
      description: Who is organizing this tournament?
      placeholder: "Enter your name"
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Information
      description: Provide an email address or Discord username for communication.
      placeholder: "Enter your email or Discord"
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Any other details or requests about the tournament?
      placeholder: "Enter any extra information here"
    validations:
      required: false
