name: Halo Tournament Creation
description: Use this template to create a custom tournament.
title: '[Tournament Proposal] <Tournament Name>'
labels:
  - Tournament
  - Proposal
assignees: Chalwk

body:
  - type: input
    id: tournament_name
    attributes:
      label: Tournament Name
      description: What is the name of the tournament?
      placeholder: "Enter the tournament name"
      required: true

  - type: dropdown
    id: tournament_type
    attributes:
      label: Tournament Type
      description: Select the type of tournament.
      options:
        - 1v1
        - 2v2
        - Team Battle (4v4)
        - Free-for-All
        - Custom (specify below)
      required: true

  - type: input
    id: custom_tournament_type
    attributes:
      label: Custom Tournament Type (if applicable)
      description: Specify the custom type if "Custom" was selected above.
      placeholder: "Enter the custom tournament type"
      required: false

  - type: input
    id: proposed_dates
    attributes:
      label: Proposed Dates
      description: When do you want the tournament to happen? Include time zones.
      placeholder: "e.g., 2025-02-10, 3 PM UTC"
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where will the tournament take place?
      options:
        - PC
        - Xbox
        - Both
      required: true

  - type: textarea
    id: custom_rules
    attributes:
      label: Custom Rules or Settings
      description: Provide any custom rules or settings for the tournament (e.g., map restrictions, time limits).
      placeholder: "Enter the rules here"
      required: false

  - type: input
    id: allowed_maps
    attributes:
      label: Allowed Maps
      description: Specify which maps are allowed (or type "All Maps").
      placeholder: "e.g., Blood Gulch, Battle Creek"
      required: true

  - type: dropdown
    id: game_mode
    attributes:
      label: Game Mode
      description: Select the game mode for the tournament.
      options:
        - Slayer
        - Capture the Flag
        - King of the Hill
        - Oddball
        - Custom (specify below)
      required: true

  - type: input
    id: max_teams
    attributes:
      label: Maximum Teams/Players
      description: What is the maximum number of teams or players allowed?
      placeholder: "Enter the maximum number"
      required: true

  - type: input
    id: registration_deadline
    attributes:
      label: Registration Deadline
      description: When should player/team registrations close?
      placeholder: "e.g., 2025-02-05, 11:59 PM UTC"
      required: true

  - type: input
    id: organizer_name
    attributes:
      label: Organizer Name
      description: `Who is organizing this tournament?`
      placeholder: "Enter your name"
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Information
      description: Provide an email address or Discord username for communication.
      placeholder: "Enter your email or Discord"
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Any other details or requests about the tournament?
      placeholder: "Enter any extra information here"
      required: false