name: 🏆 Halo Tournament Creation
description: Use this template to create a custom tournament.
title: "[Tournament Proposal] <Tournament Name>"
labels: [ "Tournament" ]
assignees: Chalwk
body:
  - type: markdown
    attributes:
      value: |
        **📌 Tournament Proposal**
        > Use this template to create a custom tournament proposal for the JeriCraft community.
        > Provide detailed information about the tournament, including the format, rules, and any other relevant details.

  - type: input
    id: tournament_name
    attributes:
      label: Tournament Name
      description: What is the name of the tournament?
      placeholder: "Enter the tournament name"
    validations:
      required: true

  - type: dropdown
    id: tournament_type
    attributes:
      label: Tournament Type
      description: Select the type of tournament.
      options:
        - 1v1
        - 2v2
        - Team Battle (4v4)
        - Free-for-All
        - Custom (specify below)
    validations:
      required: true

  - type: input
    id: custom_tournament_type
    attributes:
      label: Custom Tournament Type
      description: Specify the custom tournament type (e.g., 3v3, 5v5, etc.).
      placeholder: "Only required if 'Custom' was selected"
    validations:
      required: false

  - type: dropdown
    id: game_mode
    attributes:
      label: Game Mode
      description: Select the game mode for the tournament.
      options:
        - Slayer
        - Capture the Flag
        - King of the Hill
        - Oddball
        - Custom (specify below)
    validations:
      required: true

  - type: input
    id: custom_game_mode
    attributes:
      label: Custom Game Mode
      description: Specify the custom game mode (e.g., Custom Snipers, Pistols Only, etc.).
      placeholder: "Only required if 'Custom' above was selected"
    validations:
      required: false

  - type: dropdown
    id: format
    attributes:
      label: Tournament Format
      description: Select the tournament format.
      options:
        - Single Elimination
        - Double Elimination
        - Round Robin
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: custom_format
    attributes:
      label: Custom Format
      description: Specify the custom tournament format (e.g., Swiss, Ladder, Seeding, Pool Play, Best of X, etc.).
      placeholder: "Only required if 'Other' was selected"
    validations:
      required: false

  - type: input
    id: number_of_teams
    attributes:
      label: Number of Teams
      description: How many teams will participate in the tournament?
      placeholder: "Enter the number of teams"
    validations:
      required: true

  - type: input
    id: number_of_rounds
    attributes:
      label: Number of Rounds
      description: How many rounds will the tournament have?
      placeholder: "Enter the number of rounds"
    validations:
      required: true

  - type: input
    id: max_players
    attributes:
      label: Maximum Players
      description: What is the maximum number of players allowed?
      placeholder: "Enter the maximum number"
    validations:
      required: true

  - type: input
    id: proposed_dates
    attributes:
      label: Proposed Dates
      description: When do you want the tournament to happen? Include time zones.
      placeholder: "e.g., 2025-02-10, 3 PM UTC"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where will the tournament take place?
      options:
        - PC
        - CE
        - Both
    validations:
      required: true

  - type: textarea
    id: custom_rules
    attributes:
      label: Custom Rules or Settings
      description: Provide any custom rules or settings for the tournament (e.g., map restrictions, time limits).
      placeholder: "Enter the rules here"
    validations:
      required: false

  - type: input
    id: allowed_maps
    attributes:
      label: Allowed Maps
      description: Specify which maps are allowed (or type "All Maps").
      placeholder: "e.g., Blood Gulch, Battle Creek"
    validations:
      required: true

  - type: input
    id: registration_deadline
    attributes:
      label: Registration Deadline
      description: When should player/team registrations close?
      placeholder: "e.g., 2025-02-05, 11:59 PM UTC"
    validations:
      required: true

  - type: input
    id: organizer_name
    attributes:
      label: Organizer Name
      description: Who is organizing this tournament?
      placeholder: "Enter your name"
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Information
      description: Provide an email address or Discord username for communication.
      placeholder: "Enter your email or Discord"
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Any other details or requests about the tournament?
      placeholder: "Enter any extra information here"
    validations:
      required: false

  - type: input
    id: match_length
    attributes:
      label: Match Length
      description: How long should each match last?
      placeholder: "e.g., 10 minutes, 15 minutes, Best of 3 rounds"
    validations:
      required: true

  - type: textarea
    id: team_list
    attributes:
      label: Team List
      description: "Provide the list of teams and their members (e.g., Team A: Player 1, Player 2, etc.)."
      placeholder: "Enter team names and members here"
    validations:
      required: true

  - type: textarea
    id: tie_breaking_rules
    attributes:
      label: Tie-breaking Rules
      description: How will ties be resolved in the tournament?
      placeholder: "e.g., sudden death, overtime"
    validations:
      required: false

  - type: textarea
    id: prize_details
    attributes:
      label: Prize Information
      description: What prizes or rewards are available for winners?
      placeholder: "e.g., gift cards, bragging rights, money, etc."
    validations:
      required: false