name: Check for Broken Links

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'  # Only checks markdown files

  pull_request:
    paths:
      - '**/*.md'  # Only checks markdown files in PRs
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Link Checker
        uses: lydell/link-check-action@v1
        with:
          files: '**/*.md'
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for permissions