name: Broken Link Check

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'  # Adjusted to only check markdown files
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'  # Only check markdown files in PRs

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Broken Link Checker
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: 'https://github.com/${{ github.repository }}'
          RECURSIVE: true  # Set to true to check links on multiple pages
          TITLE: 'Broken link found (${URL})'  # Custom title for issues
          BODY: 'This link is broken and needs fixing: ${URL}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}